//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{

    public partial class AUTH : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        uint fI_Status;
        public uint I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<uint>(nameof(I_Status), ref fI_Status, value); }
        }
        USER fUser;
        [Association(@"AUTHReferencesUSER")]
        public USER User
        {
            get { return fUser; }
            set { SetPropertyValue<USER>(nameof(User), ref fUser, value); }
        }
        ROLE fRole;
        [Association(@"AUTHReferencesROLE")]
        public ROLE Role
        {
            get { return fRole; }
            set { SetPropertyValue<ROLE>(nameof(Role), ref fRole, value); }
        }
    }

}
