//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp.DC;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{
    [DefaultClassOptions]
    [System.ComponentModel.DisplayName("Chi tiết đơn hàng")]
    public partial class ORDER_DETAIL : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        ORDER fOrder;
        public ORDER Order
        {
            get { return fOrder; }
            set { SetPropertyValue<ORDER>(nameof(Order), ref fOrder, value); }
        }
        PRODUCT fProduct;
        [Association(@"ORDER_DETAILReferencesPRODUCT")]
        [XafDisplayName("Tên sản phẩm")]
        public PRODUCT Product
        {
            get { return fProduct; }
            set {
                SetPropertyValue<PRODUCT>(nameof(Product), ref fProduct, value);
               // bool isModified = SetPropertyValue<PRODUCT>(nameof(Product), ref fProduct, value); 
                //if(isModified && IsLoading && value != null)
                    
            }
        }
        int fI_Quatity;
        [XafDisplayName("Số lượng")]
        public int I_Quatity
        {
            get { return fI_Quatity; }
            set { SetPropertyValue<int>(nameof(I_Quatity), ref fI_Quatity, value); }
        }
        string fF_Price;
        [XafDisplayName("Giá tiền")]
        public string F_Price
        {
            get { return fF_Price; }
            set { SetPropertyValue<string>(nameof(F_Price), ref fF_Price, value); }
        }
        DateTime fD_Date_New;
        public DateTime D_Date_New
        {
            get { return fD_Date_New; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_New), ref fD_Date_New, value); }
        }
        DateTime fD_Date_Mod;
        public DateTime D_Date_Mod
        {
            get { return fD_Date_Mod; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_Mod), ref fD_Date_Mod, value); }
        }
        [Association(@"ORDERReferencesORDER_DETAIL")]
        public XPCollection<ORDER> ORDERs { get { return GetCollection<ORDER>(nameof(ORDERs)); } }
    }

}
