//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp.DC;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{
    [DefaultClassOptions]
    [System.ComponentModel.DisplayName("Đơn hàng")]
    public partial class ORDER : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        int fI_Status;
        public int I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<int>(nameof(I_Status), ref fI_Status, value); }
        }
        int fI_Type;
        public int I_Type
        {
            get { return fI_Type; }
            set { SetPropertyValue<int>(nameof(I_Type), ref fI_Type, value); }
        }
        string fT_Code;
        public string T_Code
        {
            get { return fT_Code; }
            set { SetPropertyValue<string>(nameof(T_Code), ref fT_Code, value); }
        }
        string fT_Info_01;
       
        public string T_Info_01
        {
            get { return fT_Info_01; }
            set { SetPropertyValue<string>(nameof(T_Info_01), ref fT_Info_01, value); }
        }
        string fT_Info_02;
        public string T_Info_02
        {
            get { return fT_Info_02; }
            set { SetPropertyValue<string>(nameof(T_Info_02), ref fT_Info_02, value); }
        }
        USER fUser;
        [Association(@"ORDERReferencesUSER")]
        [XafDisplayName("Tên người mua")]
        public USER User
        {
            get { return fUser; }
            set { SetPropertyValue<USER>(nameof(User), ref fUser, value); }
        }
        string fD_Date_New;
        public string D_Date_New
        {
            get { return fD_Date_New; }
            set { SetPropertyValue<string>(nameof(D_Date_New), ref fD_Date_New, value); }
        }
        string fD_Date_Mod;
        public string D_Date_Mod
        {
            get { return fD_Date_Mod; }
            set { SetPropertyValue<string>(nameof(D_Date_Mod), ref fD_Date_Mod, value); }
        }
        [Association(@"ORDERReferencesORDER_DETAIL")]
        public XPCollection<ORDER_DETAIL> ORDER_DETAILs { get { return GetCollection<ORDER_DETAIL>(nameof(ORDER_DETAILs)); } }
    }

}
