//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{
    [DefaultClassOptions]
    [System.ComponentModel.DisplayName("Sản phẩm")]
    public partial class PRODUCT : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        uint fI_Status;
        public uint I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<uint>(nameof(I_Status), ref fI_Status, value); }
        }
        string fT_Name;
        
        public string T_Name
        {
            get { return fT_Name; }
            set { SetPropertyValue<string>(nameof(T_Name), ref fT_Name, value); }
        }
        string fT_Code;
        public string T_Code
        {
            get { return fT_Code; }
            set { SetPropertyValue<string>(nameof(T_Code), ref fT_Code, value); }
        }
        decimal fF_Price;
        public decimal F_Price
        { 
            get { return fF_Price; }
            set { SetPropertyValue<decimal>(nameof(F_Price), ref fF_Price, value); }
        }
        string fT_Decription;
        public string T_Decription
        {
            get { return fT_Decription; }
            set { SetPropertyValue<string>(nameof(T_Decription), ref fT_Decription, value); }
        }
        CATEGORY fCategory;
        public CATEGORY Category    
        {
            get { return fCategory; }
            set { SetPropertyValue<CATEGORY>(nameof(Category), ref fCategory, value); }
        }
        string fT_Infor_01;
        public string T_Infor_01
        {
            get { return fT_Infor_01; }
            set { SetPropertyValue<string>(nameof(T_Infor_01), ref fT_Infor_01, value); }
        }
        string fT_Infor_02;
        public string T_Infor_02
        {
            get { return fT_Infor_02; }
            set { SetPropertyValue<string>(nameof(T_Infor_02), ref fT_Infor_02, value); }
        }
        DateTime fD_Date_New;
        public DateTime D_Date_New
        {
            get { return fD_Date_New; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_New), ref fD_Date_New, value); }
        }
        DateTime fD_Date_Mod;
        public DateTime D_Date_Mod
        {
            get { return fD_Date_Mod; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_Mod), ref fD_Date_Mod, value); }
        }
        [Association(@"CATEGORYReferencesPRODUCT")]
        public XPCollection<CATEGORY> CATEGORies { get { return GetCollection<CATEGORY>(nameof(CATEGORies)); } }
        [Association(@"ORDER_DETAILReferencesPRODUCT"), Aggregated]
        public XPCollection<ORDER_DETAIL> ORDER_DETAILs { get { return GetCollection<ORDER_DETAIL>(nameof(ORDER_DETAILs)); } }
        [Association(@"STOCKReferencesPRODUCT"), Aggregated]
        public XPCollection<STOCK> STOCKs { get { return GetCollection<STOCK>(nameof(STOCKs)); } }
    }

}
