//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{

    public partial class ROLE : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        uint fI_Status;
        public uint I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<uint>(nameof(I_Status), ref fI_Status, value); }
        }
        string fT_Name;
        public string T_Name
        {
            get { return fT_Name; }
            set { SetPropertyValue<string>(nameof(T_Name), ref fT_Name, value); }
        }
        string fT_Description;
        public string T_Description
        {
            get { return fT_Description; }
            set { SetPropertyValue<string>(nameof(T_Description), ref fT_Description, value); }
        }
        string fT_Right;
        public string T_Right
        {
            get { return fT_Right; }
            set { SetPropertyValue<string>(nameof(T_Right), ref fT_Right, value); }
        }
        [Association(@"AUTHReferencesROLE"), Aggregated]
        public XPCollection<AUTH> AUTHs { get { return GetCollection<AUTH>(nameof(AUTHs)); } }
    }

}
