//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
using DevExpress.ExpressApp.DC;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{
    [DefaultClassOptions]
    [System.ComponentModel.DisplayName("Kho")]
    public partial class STOCK : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        string fI_Status;
        public string I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<string>(nameof(I_Status), ref fI_Status, value); }
        }
        PRODUCT fProduct;
        [Association(@"STOCKReferencesPRODUCT")]
        public PRODUCT Product
        {
            get { return fProduct; }
            set { SetPropertyValue<PRODUCT>(nameof(Product), ref fProduct, value); }
        }
        WAREHOUSE fWarehouse;
        [Association(@"STOCKReferencesWAREHOUSE")]
        public WAREHOUSE Warehouse
        {
            get { return fWarehouse; }
            set { SetPropertyValue<WAREHOUSE>(nameof(Warehouse), ref fWarehouse, value); }
        }
        DateTime fD_Date_New;
        public DateTime D_Date_New
        {
            get { return fD_Date_New; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_New), ref fD_Date_New, value); }
        }
        DateTime fD_Date_Mod;
        public DateTime D_Date_Mod
        {
            get { return fD_Date_Mod; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_Mod), ref fD_Date_Mod, value); }
        }
    }

}
