//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{
    [DefaultClassOptions]
    public partial class USER : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        uint fI_Status;
        public uint I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<uint>(nameof(I_Status), ref fI_Status, value); }
        }
        string fT_Username;
        public string T_Username
        {
            get { return fT_Username; }
            set { SetPropertyValue<string>(nameof(T_Username), ref fT_Username, value); }
        }
        string fT_Password;
        public string T_Password
        {
            get { return fT_Password; }
            set { SetPropertyValue<string>(nameof(T_Password), ref fT_Password, value); }
        }
        string fT_Email;
        public string T_Email
        {
            get { return fT_Email; }
            set { SetPropertyValue<string>(nameof(T_Email), ref fT_Email, value); }
        }
        string fT_Tel;
        public string T_Tel
        {
            get { return fT_Tel; }
            set { SetPropertyValue<string>(nameof(T_Tel), ref fT_Tel, value); }
        }
        DateTime fD_Date_New;
        public DateTime D_Date_New
        {
            get { return fD_Date_New; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_New), ref fD_Date_New, value); }
        }
        DateTime fD_Date_Mod;
        public DateTime D_Date_Mod
        {
            get { return fD_Date_Mod; }
            set { SetPropertyValue<DateTime>(nameof(D_Date_Mod), ref fD_Date_Mod, value); }
        }
        [Association(@"AUTHReferencesUSER"), Aggregated]
        public XPCollection<AUTH> AUTHs { get { return GetCollection<AUTH>(nameof(AUTHs)); } }
        [Association(@"ORDERReferencesUSER"), Aggregated]
        public XPCollection<ORDER> ORDERs { get { return GetCollection<ORDER>(nameof(ORDERs)); } }
    }

}
