//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace Minimart_project.Module.BusinessObjects.QLmnm
{
    [DefaultClassOptions]
    public partial class WAREHOUSE : XPObject
    {
        string fI_ID;
        public string I_ID
        {
            get { return fI_ID; }
            set { SetPropertyValue<string>(nameof(I_ID), ref fI_ID, value); }
        }
        uint fI_Status;
        public uint I_Status
        {
            get { return fI_Status; }
            set { SetPropertyValue<uint>(nameof(I_Status), ref fI_Status, value); }
        }
        string fT_Name;
        public string T_Name
        {
            get { return fT_Name; }
            set { SetPropertyValue<string>(nameof(T_Name), ref fT_Name, value); }
        }
        string fT_Code;
        public string T_Code
        {
            get { return fT_Code; }
            set { SetPropertyValue<string>(nameof(T_Code), ref fT_Code, value); }
        }
        string fT_Info_01;
        public string T_Info_01
        {
            get { return fT_Info_01; }
            set { SetPropertyValue<string>(nameof(T_Info_01), ref fT_Info_01, value); }
        }
        string fT_Info_02;
        public string T_Info_02
        {
            get { return fT_Info_02; }
            set { SetPropertyValue<string>(nameof(T_Info_02), ref fT_Info_02, value); }
        }
        [Association(@"STOCKReferencesWAREHOUSE"), Aggregated]
        public XPCollection<STOCK> STOCKs { get { return GetCollection<STOCK>(nameof(STOCKs)); } }
    }

}
